#!/bin/bash
BLUE='\033[1;34m'
NC='\033[0m'

# Use https://patorjk.com/software/taag
# I like Art Font: Graceful
echo -e "${BLUE}"
cat << 'BANNER'
 ____   __   __ _  __ _  ____  ____ 
(  _ \ / _\ (  ( \(  ( \(  __)(  _ \
 ) _ (/    \/    //    / ) _)  )   /
(____/\_/\_/\_)__)\_)__)(____)(__\_)
BANNER
echo -e "${NC}"
