#!/bin/bash
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${GREEN}Network${NC}"

ip -4 addr show | grep "inet " | grep -v "127.0.0.1" | awk '{print $2}' | cut -d'/' -f1 | while read IP; do
    echo -e "  IPv4: ${IP}"
done

ip -6 addr show | grep "inet6" | grep -v "::1" | grep -v "fe80::" | awk '{print $2}' | cut -d'/' -f1 | while read IP; do
    echo -e "  IPv6: ${BLUE}${IP}${NC}"
done

echo ""
